version: '3'

services:
    demo:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: demo
        ports:
            - 8080:80   # Apache
        volumes:
            - ./../:/var/www/html/
        depends_on:
            - db-demo
        links:
          - db-demo:mysql

    phpmyadmin-demo:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-demo
        links:
            - db-demo:mysql
        ports:
            - 8082:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: Pass123
            PMA_HOST: mysql
            UPLOAD_LIMIT: 2G

    db-demo:
        image: mysql:8.0
        container_name: db-demo
        environment:
            MYSQL_DATABASE: demo
            MYSQL_ROOT_PASSWORD: Pass123
        volumes:
            # server is empty at the start because it uses RAM to store data
            - data:/var/cache
            - data:/var/lib/mysql
            # for SQL commands to be run after the server starts
            - ./sql:/docker-entrypoint-initdb.d

volumes:
    data:
        driver_opts:
            type: tmpfs
            device: tmpfs