name: Test

on: push

jobs:
    php-related-tests:
        name: PHP-related Tests (using PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php-versions: ['8.3']

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: Pass123
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_DATABASE: db_temp_init
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -pPass123"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup SSH Key
                uses: webfactory/ssh-agent@v0.9.1
                with:
                    ssh-private-key: ${{ secrets.COMMON_GITHUB_REPO_SSH_PRIVATE_KEY }}

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: iconv
                    coverage: xdebug
                    ini-values: memory_limit=1G
                    tools: flex

            -   name: Install Composer dependencies
                run: composer update -n --no-progress --no-suggest --prefer-dist --optimize-autoloader

            -   name: Prepare folders
                run: mkdir -m 0777 -p var/cache

            -   name: MySQL ...
                run: |
                  for i in {1..30}; do
                    if mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -pPass123 --silent; then
                      echo "MySQL is ready!"
                      break
                    fi
                    echo "Wait for MySQL ..."
                    sleep 2
                  done

            -   name: Create database
                run: |
                  mysql -h 127.0.0.1 -uroot -pPass123 -P 3306 -e "CREATE DATABASE IF NOT EXISTS demo;"

            -   name: PHPUnit (Tests)
                run: bin/phpunit
                env:
                    DB_HOST: 127.0.0.1
